<?php

return [
    'e_locus' => [
        'EE' => [1, 33],
        'Ee' => [34, 66],
        'ee' => [67, 100],
    ],

    'a_locus' => [
        'A+A+' => [1, 20],
        'A+a' => [21, 50],
        'aa' => [51, 100],
    ],

    'modifiers' => [
        'Flaxen' => ['roll_max' => 50, 'geno' => ''],
        'Cream_Pearl' => ['roll_max' => 20, 'geno' => 'nCr', 'geno_double' => 'CrCr'],
        'Dun' => ['roll_max' => 30, 'geno' => 'nD', 'geno_double' => 'DD'],
        'Silver' => ['roll_max' => 10, 'geno' => 'nZ', 'geno_double' => 'ZZ'],
        'Pangare' => ['roll_max' => 40, 'geno' => ''],
        'Champagne' => ['roll_max' => 15, 'geno' => 'nCh', 'geno_double' => 'ChCh'],
        'Grey' => ['roll_max' => 25, 'geno' => 'nG', 'geno_double' => 'GG'],
        'Rabicano' => ['roll_max' => 20, 'geno' => 'nRb'],
        'Splash' => ['roll_max' => 15, 'geno' => 'nSpl'],
        'Tobiano' => ['roll_max' => 25, 'geno' => 'nT', 'geno_double' => 'TT'],
        'Overo' => ['roll_max' => 5, 'geno' => 'nO'],
    ],

    'base_coat' => [
        0 => 'Chestnut',
        1 => 'Black',
        2 => 'Wild Bay',
        3 => 'Bay',
        4 => 'Seal Bay',
        5 => 'Palomino',
        6 => 'Smoky Black',
        7 => 'Wild Buckskin',
        8 => 'Buckskin',
        9 => 'Burnt Buckskin',
        10 => 'Cremello',
        11 => 'Smoky Cream',
        12 => 'Wild Perlino',
        13 => 'Perlino',
        14 => 'Burnt Perlino',
        15 => 'Palomino Pearl',
        16 => 'Smoky Black Pearl',
        17 => 'Wild Buckskin Pearl',
        18 => 'Buckskin Pearl',
        19 => 'Burnt Buckskin Pearl',
        20 => 'Apricot Pearl',
        21 => 'Black Pearl',
        22 => 'Wild Bay Pearl',
        23 => 'Bay Pearl',
        24 => 'Burnt Bay Pearl',
        25 => 'Chestnut (Pearl Carrier)',
        26 => 'Black (Pearl Carrier)',
        27 => 'Wild Bay (Pearl Carrier)',
        28 => 'Bay (Pearl Carrier)',
        29 => 'Seal Bay (Pearl Carrier)',
        30 => 'Apricot Dun',
        31 => 'Grullo',
        32 => 'Wild Classic Dun',
        33 => 'Classic Dun',
        34 => 'Brown Dun',
        35 => 'Dunalino',
        36 => 'Smoky Grullo',
        37 => 'Wild Dunskin',
        38 => 'Dunskin',
        39 => 'Brown Dunskin',
        40 => 'Cremello Dun',
        41 => 'Smoky Cream Dun',
        42 => 'Wild Perlino Dun',
        43 => 'Perlino Dun',
        44 => 'Burnt Perlino Dun',
        45 => 'Dunalino Pearl',
        46 => 'Smoky Grullo Pearl',
        47 => 'Wild Dunskin Pearl',
        48 => 'Dunskin Pearl',
        49 => 'Brown Dunskin Pearl',
        50 => 'Apricot Pearl Dun',
        51 => 'Grullo Pearl',
        52 => 'Wild Classic Dun Pearl',
        53 => 'Classic Dun Pearl',
        54 => 'Brown Dun Pearl',
        55 => 'Apricot Dun (Pearl Carrier)',
        56 => 'Grullo (Pearl Carrier)',
        57 => 'Wild Classic Dun (Pearl Carrier)',
        58 => 'Classic Dun (Pearl Carrier)',
        59 => 'Brown Dun (Pearl Carrier)',
        60 => 'Gold Champange',
        61 => 'Classic Champagne',
        62 => 'Wild Amber Champagne',
        63 => 'Amber Champange',
        64 => 'Sable Champagne',
        65 => 'Gold Cream Champagne',
        66 => 'Classic Cream Champagne',
        67 => 'Wild Amber Cream Champagne',
        68 => 'Amber Cream Champagne',
        69 => 'Sable Amber Cream Champagne',
        70 => 'Cremello Champagne',
        71 => 'Smoky Cream Champagne',
        72 => 'Wild Perlino Champagne',
        73 => 'Perlino Champagne',
        74 => 'Burnt Perlino Champagne',
        75 => 'Palomino Pearl Champange',
        76 => 'Smoky Black Pearl Champagne',
        77 => 'Wild Buckskin Pearl Champagne',
        78 => 'Buckskin Pearl Champagne',
        79 => 'Burnt Buckskin Pearl Champagne',
        80 => 'Apricot Pearl Champagne',
        81 => 'Black Pearl Champagne',
        82 => 'Wild Bay Pearl Champagne',
        83 => 'Bay Pearl Champagne',
        84 => 'Burnt Bay Pearl Champagne',
        85 => 'Gold Champagne (Pearl Carrier)',
        86 => 'Classic Champagne (Pearl Carrier)',
        87 => 'Wild Amber Champagne (Pearl Carrier)',
        88 => 'Amber Champagne (Pearl Carrier)',
        89 => 'Sable Champagne (Pearl Carrier)',
        90 => 'Gold Champagne Dun',
        91 => 'Classic Champagne Dun',
        92 => 'Wild Amber Champagne Dun',
        93 => 'Amber Champagne Dun',
        94 => 'Gold Cream Champagne Dun',
        95 => 'Classic Cream Champagne Dun',
        96 => 'Wild Amber Cream Champagne Dun',
        97 => 'Amber Cream Champagne Dun',
        98 => 'Sable Amber Cream Champagne Dun',
        99 => 'Cremello Champagne Dun',
        100 => 'Smoky Cream Champagne Dun',
    ],
];
